- alias: Allume la lampe a la tombee de la nuit
  trigger:
    platform: sun
    event: sunset
    offset: "-00:10:00"
  condition:
#    - condition: state
#    entity_id: device_tracker.nut
#    state: home
    - condition: state
      entity_id: input_boolean.lumieresalon
      state: 'on'
    - condition: state
      entity_id: sensor.broadlinklight 
      state: 'noir'
  action:
    service: switch.turn_on
    entity_id: switch.lampe_salon
- alias: fermer les volets du salon quand la nuit tombe
  trigger:
    platform: sun
    event: sunset
    offset: "-00:10:00"
  condition:
    - condition: state
      entity_id: input_boolean.volets
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.volet_salon
    - service: notify.notifier_seb
      data:
        message: Les volets du salon sont fermes !
- alias: ouvrir les volets du salon quand le jour se leve
  trigger:
    platform: sun
    event: sunrise
  condition:
    - condition: state
      entity_id: input_boolean.volets
      state: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.volet_salon
- alias: Poubelles a sortir
  trigger:
    platform: state
    entity_id: sensor.poubelles
    to: 'on'
    from: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.poubelles
      state: 'on'
  action:
    - service: notify.notifier_seb
      data:
        message: 'Monsieur, il faudrait sortir les {{ states.calendar.ordures.attributes.message }}.'
    - service: notify.notifier_klem
      data:
        message: 'Mademoiselle, il faudrait sortir les {{ states.calendar.ordures.attributes.message }}.'

