homeassistant:
  name: Home
  latitude: 44.8101
  longitude: -0.6413
  elevation: 39
  unit_system: metric
  time_zone: Europe/Paris
  customize: !include customize.yaml


#introduction:

#frontend:

http:
#  api_password: 150216
#  ssl_certificate: /etc/letsencrypt/live/kleans.duckdns.org/fullchain.pem
#  ssl_key: /etc/letsencrypt/live/kleans.duckdns.org/privkey.pem
#  base_url: kleans.duckdns.org:8123
#  base_url: kleans.duckdns.org:443

updater:

discovery:

conversation:

history:

logbook:

sun:

device_tracker:
  - platform: bluetooth_le_tracker
google:
  client_id: 612631300023-ji3q2iopvtepq4cusdsip8m001q29m21.apps.googleusercontent.com
  client_secret: pivmq-T1XzSujXD9rxHB8c3r

notify:
  - name: notifier_seb
    platform: telegram
    api_key: 324726208:AAFID-JexILPVFCqGoS2EIPLc3zG0AMXEiU
    chat_id: 258006500
  - name: notifier_klem
    platform: telegram
    api_key: 324726208:AAFID-JexILPVFCqGoS2EIPLc3zG0AMXEiU
    chat_id: 371727511 

sensor: !include sensor.yaml

tts:
  platform: google
  language: 'fr'
  cache: true
  cache_dir: /tmp/tts
  time_memory: 300

switch:
  - platform: broadlink
    host: 192.168.0.25
    mac: '34:ea:34:e7:d3:de'
    name: 'switch broadlink'
    switches:
      tv_lg:
        friendly_name: 'TV LG Salon'
        command_on: 'JgBQAAABJ5MTEhISEzcTEhMSExETEhMSEzYUNhMSEzYTNxM3EzYTNxMSExETEhM3ExITERMSExITNxM2EzcTEhM2EzcTNhM3EwAFQQABJ0gTAA0FAAAAAAAAAAA='
        command_off: 'JgBQAAABJ5MTEhISEzcTEhMSExETEhMSEzYUNhMSEzYTNxM3EzYTNxMSExETEhM3ExITERMSExITNxM2EzcTEhM2EzcTNhM3EwAFQQABJ0gTAA0FAAAAAAAAAAA='
      volet_salon:
        friendly_name: 'volet salon'
        command_on: 'sgBgAQkJCSwJLQkJCQoJLAkKCS0ICgksCSwJCgksCQoJLAkKCQoILQkJCS0JLAkKCSwJCgksCQoJCQktCAoJLAkKCSwJCgksCQoILQkKCSwJCggsCgABXQlbCQkJLQksCQoJCQktCSwJCgkJCSwJLQkJCQoJLAkKCSwJLAkKCQoJLAksCQoJCQktCQkJLQksCQoICgktCQkJLQkJCS0JLAkJCS0ICgksCQoJCgksCQoILQksCQoJLAkKCSwJCgkJCS0JCggtCQkJLQgKCS0ICgksCQoJLAkKCSwJAAFdCVsJCggtCSwJCgkKCC0JLAkKCQkJLQksCQoJCQksCQoJLAktCQkJCgktCCwJCgkKCSwJCggtCSwJCgkJCS0JCQktCQkJLQksCQoJLAkKCSwJCggKCSwJCgksCSwJCgksCQoJLAkKCQoILQkKCSwJCQktCQkJLQkJCS0JCQktCQkJLAkABdwAAAAAAAAAAA=='
        command_off: 'sgBoAgksCQoJCggtCQoILQkKCC0JLAkKCC0JCggtCAoJCgksCQoILQksCQoJLAkKCSwJCgkJCSwJCgksCSwJCgkJCS0ICgktCQkJLAkKCSwJAAFdCVsJCQktCSwJCgkJCS0ILQgKCQoILQksCQoJCQktCAoJLQksCQoJCQksCS0JCQkKCSwJCgksCSwJCgkJCSwJCgktCQkJLQgsCQoJLAkKCSwJCgkJCS0JCQksCS0JCQktCAoJLQgKCQoILQkKCC0JLAkKCQkJLAoJCS0JCQksCQoJLAgAAWAJWwkJCS0JLAkKCAoJLQgtCQkJCgksCSwJCgkJCS0JCQktCSwJCgkJCS0ILQkKCAoJLAkKCSwJLAkKCQkJLQgKCS0JCQktCSwJCQktCAoJLAkKCQkJLQkJCS0JLAkKCSwJCggtCAsICgksCQoJLAksCQoJCQktCQkJLQgKCSwJCgksCAABXglbCQkJLQksCQoICgksCS0ICgkKCC0JLAkKCQkJLAoJCS0JLAkKCAoJLAktCAoJCgksCQkJLQksCQoICgksCQoJLQgKCSwJLAkKCSwJCgksCQoJCQksCgkJLAksCQoJLAkKCSwJCgkKCSwJCQktCSwJCggKCSwKCQksCQoJLAkJCSwJAAFdCVwJCQktCC0JCQkKCSwJLAkKCQkJLQksCQoICgksCQoJLQgtCAoJCggtCSwJCgkJCS0JCQktCC0JCQkKCSwJCgksCQoJLAksCQoJLAkKCSwJCggKCS0ICgksCSwJCgksCQoJLAkKCQkJLQgKCSwJLQkKCAoJLAkKCSwJCQktCQkJLAkABdw='
  - platform: broadlink
    host: 192.168.0.12
    mac: '34:ea:34:d9:f1:92'
    type: mp1-1
    friendly_name: 'Lampe Salon'
  - platform: broadlink
    host: 192.168.0.12
    mac: '34:ea:34:d9:f1:92'
    type: mp1-2
    name: wii
    friendly_name: 'Wii'
  - platform: broadlink
    host: 192.168.0.12
    mac: '34:ea:34:d9:f1:92'
    type: mp1-3
    friendly_name: 'Television'
  - platform: broadlink
    host: 192.168.0.12
    mac: '34:ea:34:d9:f1:92'
    type: mp1-4
    friendly_name: 'chromecast'

group: !include group.yaml

automation: !include automation.yaml

media_player:
  - platform: vlc
  - platform: cast
  - platform: plex

input_boolean:
  bonjour:
    name: Service bonjour
    initial: on
    icon: mdi:comment-text
  lumieresalon:
    name: Lumiere auto salon
    initial: on
  volets:
    name: Gestion auto des volets
    initial: on
  poubelles:
    name: Sortie des poubelles
    initial: on

script:
  annoncematin:
    alias: Matin
    sequence:
      - alias: Annonce Matin
        service: tts.google_say
        entity_id: media_player.vlc
        data_template:
          message: "{{ ['Bonjour','Comment allez vous?','Heureux de vous voir'] | random }} . La météo prévoit, {{ states.sensor.meteotoday.state }} pour aujourd'hui. La température extérieure est de {{ states.sensor.tempext_temperature.state | round }} degrés."
  demarre_robot_aspi:
    alias: Demarre Robot Aspirateur
    sequence:
      - service: broadlink.send_packet_192_168_0_25
        data:
          packet:
# bouton power            - "JgAwApSREjcSEhMSEhITEhISExISNhM2ExITERMSExETEhMREzYTEhMRExITERMSExETEhISEzYTNhM2EzYTNhM2EzYTNhMAA7aTkRM2ExITERMSExETEhMREzYTNhMSExETEhISExISEhM2ExETEhMRExITERMSExETEhM2EzYTNhM2EjcSNxI3EjYTAAO2lJETNhMSEhITEhISExISEhM2EzYTERMSExETEhMRExITNhMRExITERMSExETEhISExISNxI3EjYTNhM2EzYTNhM2EwADtpSREzYTERMSExETEhMRExITNhM2ExETEhMRExISEhMSEjcSEhMSEhITEhISExETEhMREzYTNhM2EzYTNhM2EzYTNhMAA7aUkRM2ExETEhMRExISEhMSEjcSNxISExISEhMRExITERM2ExITERMSExETEhMRExITERM2EzYTNhM2EzYTNhM2EzYTAAO2k5ISNxISExISEhMSEhITEhI2EzYTEhMRExITERMSExETNhMSExETEhISExISEhMSEhITNhM2EzYTNhM2EzYTNhM2EwADtpOREzYTEhMRExITERMSExETNhM2ExISEhMSEhITEhISEzYTEhISExETEhMRExITERMSEzYTNhM2EzYSNxI3EjcSNhMAA7aUkRM2ExISEhMSEhITEhISEzYTNhMSEhITERMSExETEhM2ExETEhMRExITERMSEhITEhI3EjcSNhM3EjYTNhM2EzYTAA0FExITERMSEzY="
            - "JgDSAJSREzYTEhISExISEhMSEhITNhM2ExETEhMRExITERMSEzYTERMSExETNhMSExETEhISEzYTNhM2ExETNhM2EzYTNhMAA7aUkRM2ExETEhMRExITERMSEzYTNhMRExITERMSExETEhM2EhITEhISEzYTEhISExETEhM2EzYTNhMREzYTNhM2EzYTAAO2lJETNhMRExITERMSExETEhM2EzYTERMSEhITEhISExISNhMSExETEhM2ExETEhMRExITNhM2EzYTERM2EzYTNhM2EwANBQAAAAAAAA=="
  demarre_tv_cast:
    alias: Demarre TV pour chromecast
    sequence:
      - service: broadlink.send_packet_192_168_0_25
        data:
          packet:
            - "JgBQAAABJ5MTEhISEzcTEhMSExETEhMSEzYUNhMSEzYTNxM3EzYTNxMSExETEhM3ExITERMSExITNxM2EzcTEhM2EzcTNhM3EwAFQQABJ0gTAA0FAAAAAAAAAAA="
            - "JgBQAAABJJMSEhISETgSEhITEBMSEhMSETcSNxMREjcSNxI3EjcSOBETERITNhM2EhITERM2EzcRNxI3ExISEhI3EjcRExETEgAFLQABJEoRAA0FAAAAAAAAAAA="

