homeassistant:
  name: Home
  latitude: 44.8101
  longitude: -0.6413
  elevation: 39
  unit_system: metric
  time_zone: Europe/Paris
  customize: !include customize.yaml

#http:

updater:

discovery:

conversation:

history:

# Recorder
recorder:
  purge_days: 7
  exclude:
    domains:
      - updater
      - automation

logbook:

sun:

device_tracker:
  - platform: tplink
    host: !secret tplink_ip
    username: !secret tplink_user
    password: !secret tplink_pass
    interval_seconds: 120
    consider_home: 180
    track_new_devices: yes

google:
  client_id: !secret google_id
  client_secret: !secret google_secret

telegram_bot:
  - platform: polling
    api_key: !secret telegram_key
    allowed_chat_ids:
      - !secret telegram_chatseb
      - !secret telegram_chatklem

notify:
  - name: notifier_seb
    platform: telegram
    chat_id: !secret telegram_chatseb
  - name: notifier_klem
    platform: telegram
    chat_id: !secret telegram_chatklem

tts:
  platform: google
  language: 'fr'
  cache: true
  cache_dir: /tmp/tts
  time_memory: 300

sensor: !include sensor.yaml
switch: !include switch.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
script: !include script.yaml
automation: !include_dir_merge_list automation
group: !include_dir_merge_named group

media_player:
  - platform: cast

input_slider: 
  alarmhour:
    name: Hour
    icon: mdi:timer
    initial: 8  
    min: 0
    max: 23
    step: 1
  alarmminutes:
    name: Minutes
    icon: mdi:timer
    initial: 0
    min: 0
    max: 55
    step: 5

