- platform: broadlink
  update_interval: 60
  host: 192.168.0.23
  mac: '34:ea:34:e5:30:dc'
  monitored_conditions:
    - temperature
    - humidity
    - air_quality
    - light
    - noise
- platform: yweather
  woeid: 22145400
  forecast: 1
  monitored_conditions:
    - weather
    - weather_current
    - temp_min
    - temp_max
    - wind_speed
    - pressure
    - visibility
    - humidity
    - temperature
- platform: yweather
  woeid: 22145400
  name: ymeteotoday
  monitored_conditions:
    - wind_speed
    - visibility
    - humidity
    - temperature
- platform: template
  sensors:
    forecast:
      friendly_name: 'Previsions pour demain'
      value_template: >
        {%- if (states.sensor.yweather_condition.state == "tornado") -%}
        des tornades
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Tropical Storm") -%}
        des tempetes tropicales
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Hurricane") -%}
        des ouragans
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Severe Thunderstorms") -%}
        des orages importants
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Thunderstorms") -%}
        des orages
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Mixed Rain And Snow") -%}
        de la pluie et de la neige
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Mixed Rain And Sleet") -%}
        de la pluie et de la neige fondue
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Mixed Snow And Sleet") -%}
        de la neige fondue
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Freezing Drizzle") -%}
        des bruines verglassantes
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Drizzle") -%}
        de la bruine
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Freezing Rain") -%}
        des pluies verglassantes
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Showers") -%}
        de la pluie
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Snow Flurries") -%}
        des averses de neige 
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Light Snow Showers") -%}
        des averses de neige en petite quantité
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Blowing Snow") -%}
        de la neige
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Snow") -%}
        de la neige
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Hail") -%}
        de la grêle
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Sleet") -%}
        de la neige fondue
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Dust") -%}
        de la poussiere
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Foggy") -%}
        du brouillard
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Haze") -%}
        de la brume
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Smoky") -%}
        de la brume
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Blustery") -%}
        des tempétes
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Windy") -%}
        du vent
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Cold") -%}
        un temps froid
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Cloudy") -%}
        un temps nuageux
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Mostly Cloudy \(Night\)") -%}
        un temps plutot nuageux en soirée
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Mostly Cloudy \(Day\)") -%}
        un temps plutot nuageux en journée
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Mostly Cloudy") -%}
        un temps plutot nuageux
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Partly Cloudy") -%}
        un temps un peu nuageux
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Partly Cloudy \(Night\)") -%}
        un temps un peu nuageux en soirée
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Partly Cloudy \(Day\)") -%}
        un temps un peu nuageux en journée
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Clear \(Night\)") -%}
        un temps clair en soirée
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Sunny") -%}
        un temps ensoleillé
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Fair \(Night\)") -%}
        un temps mitigé en soirée
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Fair \(Day\)") -%}
        un temps mitigé en journée
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Mixes Rain And Hail") -%}
        de la grêle et de la pluie melée
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Hot") -%}
        un temps chaud
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Isolated Thunderstorms") -%}
        des orages isolées
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Scattered Thunderstorms") -%}
        des orages éparses
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Scattered Showers") -%}
        des averses éparses
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Heavy Snow") -%}
        beaucoup de neige
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Scattered Snow Showers") -%}
        des chute de neige éparses
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Thundershowers") -%}
        beaucoup d'orages
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Snow Showers") -%}
        des chutes de neige
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Isolated Thundershowers") -%}
        des orages isolés
        {%- endif %}
        {%- if (states.sensor.yweather_condition.state == "Clear") -%}
        un temps dégagé
        {%- endif %}
      icon_template: mdi:weather-partlycloudy

- platform: template
  sensors:
    meteotoday:
      friendly_name: 'Meteo de la journée'
      value_template: >
        {%- if (states.sensor.yweather_current.state == "Clear") -%}
        un temps dégagé
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "tornado") -%}
        des tornades
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Tropical Storm") -%}
        des tempetes tropicales
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Hurricane") -%}
        des ouragans
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Severe Thunderstorms") -%}
        des orages importants
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Thunderstorms") -%}
        des orages
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Mixed Rain And Snow") -%}
        de la pluie et de la neige
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Mixed Rain And Sleet") -%}
        de la pluie et de la neige fondue
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Mixed Snow And Sleet") -%}
        de la neige fondue
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Freezing Drizzle") -%}
        des bruines verglassantes
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Drizzle") -%}
        de la bruine
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Freezing Rain") -%}
        des pluies verglassantes
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Showers") -%}
        de la pluie
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Snow Flurries") -%}
        des averses de neige 
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Light Snow Showers") -%}
        des averses de neige en petite quantité
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Blowing Snow") -%}
        de la neige
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Snow") -%}
        de la neige
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Hail") -%}
        de la grêle
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Sleet") -%}
        de la neige fondue
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Dust") -%}
        de la poussiere
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Foggy") -%}
        du brouillard
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Haze") -%}
        de la brume
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Smoky") -%}
        de la brume
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Blustery") -%}
        des tempétes
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Windy") -%}
        du vent
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Cold") -%}
        un temps froid
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Cloudy") -%}
        un temps nuageux
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Mostly Cloudy \(Night\)") -%}
        un temps plutot nuageux en soirée
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Mostly Cloudy \(Day\)") -%}
        un temps plutot nuageux en journée
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Mostly Cloudy") -%}
        un temps plutot nuageux
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Partly Cloudy") -%}
        un temps un peu nuageux
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Partly Cloudy \(Night\)") -%}
        un temps un peu nuageux en soirée
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Partly Cloudy \(Day\)") -%}
        un temps un peu nuageux en journée
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Clear \(Night\)") -%}
        un temps clair en soirée
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Sunny") -%}
        un temps ensoleillé
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Fair \(Night\)") -%}
        un temps mitigé en soirée
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Fair \(Day\)") -%}
        un temps mitigé en journée
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Mixes Rain And Hail") -%}
        de la grêle et de la pluie melée
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Hot") -%}
        un temps chaud
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Isolated Thunderstorms") -%}
        des orages isolées
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Scattered Thunderstorms") -%}
        des orages éparses
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Scattered Showers") -%}
        des averses éparses
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Heavy Snow") -%}
        beaucoup de neige
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Scattered Snow Showers") -%}
        des chute de neige éparses
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Thundershowers") -%}
        beaucoup d'orages
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Snow Showers") -%}
        des chutes de neige
        {%- endif %}
        {%- if (states.sensor.yweather_current.state == "Isolated Thundershowers") -%}
        des orages isolés
        {%- endif %}
        {{ states.sensor.yweather_current.entity_picture }}
      icon_template: mdi:weather-partlycloudy

- platform: template
  sensors:
    globaltemp:
      friendly_name: 'Températures'
      value_template: '{{ states.sensor.yweather_temperature.state }} °C ( min. {{ states.sensor.yweather_temperature_min.state }} - max. {{ states.sensor.yweather_temperature_max.state }} )'
      icon_template: mdi:temperature-celsius

- platform: template
  sensors:
    broadlinknoise:
      friendly_name: 'Bruit'
      value_template: >
        {%- if (states.sensor.broadlink_sensor_noise.state == "0") -%}
        silencieux
        {%- endif %}
        {%- if (states.sensor.broadlink_sensor_noise.state == "1") -%}
        normal
        {%- endif %}
        {%- if (states.sensor.broadlink_sensor_noise.state == "2") -%}
        bruyant
        {%- endif %}

- platform: template
  sensors:
    broadlinklight:
      friendly_name: 'Luminosité'
      value_template: >
        {%- if (states.sensor.broadlink_sensor_light.state == "0") -%}
        noir
        {%- endif %}
        {%- if (states.sensor.broadlink_sensor_light.state == "1") -%}
        sombre
        {%- endif %}
        {%- if (states.sensor.broadlink_sensor_light.state == "2") -%}
        normal
        {%- endif %}
        {%- if (states.sensor.broadlink_sensor_light.state == "3") -%}
        lumineux
        {%- endif %}

- platform: template
  sensors:
    broadlinkair:
      friendly_name: "Qualité de l'air"
      value_template: >
        {%- if (states.sensor.broadlink_sensor_air_quality.state == "0") -%}
        excellente
        {%- endif %}
        {%- if (states.sensor.broadlink_sensor_air_quality.state == "1") -%}
        bonne
        {%- endif %}
        {%- if (states.sensor.broadlink_sensor_air_quality.state == "2") -%}
        normale
        {%- endif %}
        {%- if (states.sensor.broadlink_sensor_air_quality.state == "3") -%}
        mauvaise
        {%- endif %}

- platform: template
  sensors:
    sun_state:
      value_template: '{% if is_state("sun.sun", "above_horizon") %}levé{% else %}couché{% endif %}'
      friendly_name: 'Etat du soleil'
      icon_template: '{% if is_state("sun.sun", "above_horizon") %}mdi:weather-sunny{% else %}mdi:weather-night{% endif %}'
