- platform: broadlink
  update_interval: 60
  host: 192.168.0.23
  mac: '34:ea:34:e5:30:dc'
  monitored_conditions:
    - temperature
    - humidity
    - air_quality
    - light
    - noise
#- platform: yweather
#  woeid: 22145400
#  forecast: 1
#  monitored_conditions:
#    - weather
#    - weather_current
#    - temp_min
#    - temp_max
#    - wind_speed
#    - pressure
#    - visibility
#    - humidity
#    - temperature
- platform: yweather
  woeid: 22145400
#  name: ymeteotoday
  monitored_conditions:
    - weather_current
    - wind_speed
    - visibility
    - humidity
    - temperature
- platform: template
  sensors:
    forecast:
      friendly_name: 'Meteo'
      value_template: >
        {%- if (states.sensor.yweather_current.state == "tornado") -%} des tornades
        {%- elif (states.sensor.yweather_current.state == "Tropical Storm") -%} des tempetes tropicales
        {%- elif (states.sensor.yweather_current.state == "Hurricane") -%} des ouragans
        {%- elif (states.sensor.yweather_current.state == "Severe Thunderstorms") -%} des orages importants
        {%- elif (states.sensor.yweather_current.state == "Thunderstorms") -%} des orages
        {%- elif (states.sensor.yweather_current.state == "Mixed Rain And Snow") -%} de la pluie et de la neige
        {%- elif (states.sensor.yweather_current.state == "Mixed Rain And Sleet") -%} de la pluie et de la neige fondue
        {%- elif (states.sensor.yweather_current.state == "Mixed Snow And Sleet") -%} de la neige fondue
        {%- elif (states.sensor.yweather_current.state == "Freezing Drizzle") -%} des bruines verglassantes
        {%- elif (states.sensor.yweather_current.state == "Drizzle") -%} de la bruine
        {%- elif (states.sensor.yweather_current.state == "Freezing Rain") -%} des pluies verglassantes
        {%- elif (states.sensor.yweather_current.state == "Showers") -%} de la pluie
        {%- elif (states.sensor.yweather_current.state == "Snow Flurries") -%} des averses de neige 
        {%- elif (states.sensor.yweather_current.state == "Light Snow Showers") -%} des petites averses de neige
        {%- elif (states.sensor.yweather_current.state == "Blowing Snow") -%} de la neige
        {%- elif (states.sensor.yweather_current.state == "Snow") -%} de la neige
        {%- elif (states.sensor.yweather_current.state == "Hail") -%} de la grêle
        {%- elif (states.sensor.yweather_current.state == "Sleet") -%} de la neige fondue
        {%- elif (states.sensor.yweather_current.state == "Dust") -%} de la poussiere
        {%- elif (states.sensor.yweather_current.state == "Foggy") -%} du brouillard
        {%- elif (states.sensor.yweather_current.state == "Haze") -%} de la brume
        {%- elif (states.sensor.yweather_current.state == "Smoky") -%} de la brume
        {%- elif (states.sensor.yweather_current.state == "Windy") -%} du vent
        {%- elif (states.sensor.yweather_current.state == "Cold") -%} un temps froid
        {%- elif (states.sensor.yweather_current.state == "Cloudy") -%} un temps nuageux
        {%- elif (states.sensor.yweather_current.state == "Mostly Cloudy \(Night\)") -%} un temps plutot nuageux en soirée
        {%- elif (states.sensor.yweather_current.state == "Mostly Cloudy \(Day\)") -%} un temps plutot nuageux en journée
        {%- elif (states.sensor.yweather_current.state == "Mostly Cloudy") -%} un temps plutot nuageux
        {%- elif (states.sensor.yweather_current.state == "Partly Cloudy") -%} un temps partiellement nuageux
        {%- elif (states.sensor.yweather_current.state == "Partly Cloudy \(Night\)") -%} un temps partiellement nuageux en soirée
        {%- elif (states.sensor.yweather_current.state == "Partly Cloudy \(Day\)") -%} un temps partiellement nuageux en journée
        {%- elif (states.sensor.yweather_current.state == "Clear \(Night\)") -%} un temps clair en soirée
        {%- elif (states.sensor.yweather_current.state == "Sunny") -%} un temps ensoleillé
        {%- elif (states.sensor.yweather_current.state == "Fair \(Night\)") -%} un temps mitigé en soirée
        {%- elif (states.sensor.yweather_current.state == "Fair \(Day\)") -%} un temps mitigé en journée
        {%- elif (states.sensor.yweather_current.state == "Mixes Rain And Hail") -%} de la grêle et de la pluie melée
        {%- elif (states.sensor.yweather_current.state == "Hot") -%} un temps chaud
        {%- elif (states.sensor.yweather_current.state == "Isolated Thunderstorms") -%} des orages isolées
        {%- elif (states.sensor.yweather_current.state == "Scattered Thunderstorms") -%} des orages éparses
        {%- elif (states.sensor.yweather_current.state == "Scattered Showers") -%} des averses éparses
        {%- elif (states.sensor.yweather_current.state == "Heavy Snow") -%} beaucoup de neige
        {%- elif (states.sensor.yweather_current.state == "Scattered Snow Showers") -%} des chute de neige éparses
        {%- elif (states.sensor.yweather_current.state == "Thundershowers") -%} beaucoup d'orages
        {%- elif (states.sensor.yweather_current.state == "Snow Showers") -%} des chutes de neige
        {%- elif (states.sensor.yweather_current.state == "Isolated Thundershowers") -%} quelques orages
        {%- elif (states.sensor.yweather_current.state == "Clear") -%} un temps dégagé
        {%- elif (states.sensor.yweather_current.state == "Breezy") -%} du vent
        {%- elif (states.sensor.yweather_current.state == "Mostly Sunny") -%} un temps principalement ensoleillé
        {%- else -%} {{ states.sensor.yweather_current.state }}
        {%- endif %}
      icon_template: mdi:weather-partlycloudy

- platform: template
  sensors:
    globaltemp:
      friendly_name: 'Températures'
      value_template: '{{ states.sensor.yweather_temperature.state }} °C ( min. {{ states.sensor.yweather_temperature_min.state }} - max. {{ states.sensor.yweather_temperature_max.state }} )'
      icon_template: mdi:temperature-celsius

- platform: template
  sensors:
    broadlinknoise:
      friendly_name: 'Bruit'
      value_template: >
        {%- if (states.sensor.broadlink_sensor_noise.state == "0") -%}
        silencieux
        {%- endif %}
        {%- if (states.sensor.broadlink_sensor_noise.state == "1") -%}
        normal
        {%- endif %}
        {%- if (states.sensor.broadlink_sensor_noise.state == "2") -%}
        bruyant
        {%- endif %}

- platform: template
  sensors:
    broadlinklight:
      friendly_name: 'Luminosité'
      value_template: >
        {%- if (states.sensor.broadlink_sensor_light.state == "0") -%}
        noir
        {%- endif %}
        {%- if (states.sensor.broadlink_sensor_light.state == "1") -%}
        sombre
        {%- endif %}
        {%- if (states.sensor.broadlink_sensor_light.state == "2") -%}
        normal
        {%- endif %}
        {%- if (states.sensor.broadlink_sensor_light.state == "3") -%}
        lumineux
        {%- endif %}

- platform: template
  sensors:
    broadlinkair:
      friendly_name: "Qualité de l'air"
      value_template: >
        {%- if (states.sensor.broadlink_sensor_air_quality.state == "0") -%}
        excellente
        {%- endif %}
        {%- if (states.sensor.broadlink_sensor_air_quality.state == "1") -%}
        bonne
        {%- endif %}
        {%- if (states.sensor.broadlink_sensor_air_quality.state == "2") -%}
        normale
        {%- endif %}
        {%- if (states.sensor.broadlink_sensor_air_quality.state == "3") -%}
        mauvaise
        {%- endif %}

- platform: template
  sensors:
    sun_state:
      value_template: '{% if is_state("sun.sun", "above_horizon") %}levé{% else %}couché{% endif %}'
      friendly_name: 'Etat du soleil'
      icon_template: '{% if is_state("sun.sun", "above_horizon") %}mdi:weather-sunny{% else %}mdi:weather-night{% endif %}'
- platform: template
  sensors:
    poubelles:
      friendly_name: Poubelles
      value_template: '{% if as_timestamp(states.calendar.ordures.attributes.start_time) - as_timestamp(now().strftime("%Y-%m-%d %H:%M:%S")) < 900  %}on{% else %}off{% endif %}'
- platform: template
  sensors:
    alarm_hour:
      friendly_name: 'Hour'
      value_template: '{{ states("input_slider.alarmhour") | round(0) }}'
    alarm_minutes:
      friendly_name: 'Minutes'
      value_template: '{{ states("input_slider.alarmminutes") | round(0) }}'
    alarm_time:
      friendly_name: 'Time'
      value_template: '{{ states("sensor.alarm_hour") }}:{% if states("sensor.alarm_minutes")|length == 1 %}0{% endif %}{{ states("sensor.alarm_minutes") }}'
- platform: command_line
  name: news
  command: "cat /home/homeassistant/.homeassistant/scripts/news.txt"

- platform: command_line
  name: tf1
  command: "cat /home/homeassistant/.homeassistant/scripts/tele/tf1"

- platform: command_line
  name: fr2
  command: "cat /home/homeassistant/.homeassistant/scripts/tele/fr2"

- platform: command_line
  name: fr3
  command: "cat /home/homeassistant/.homeassistant/scripts/tele/fr3"

- platform: command_line
  name: canal
  command: "cat /home/homeassistant/.homeassistant/scripts/tele/canal"

- platform: command_line
  name: arte
  command: "cat /home/homeassistant/.homeassistant/scripts/tele/arte"

- platform: command_line
  name: m6
  command: "cat /home/homeassistant/.homeassistant/scripts/tele/m6"

- platform: command_line
  name: fr5
  command: "cat /home/homeassistant/.homeassistant/scripts/tele/fr5"

- platform: command_line
  name: c8
  command: "cat /home/homeassistant/.homeassistant/scripts/tele/c8"

- platform: command_line
  name: w9
  command: "cat /home/homeassistant/.homeassistant/scripts/tele/w9"

- platform: command_line
  name: tmc
  command: "cat /home/homeassistant/.homeassistant/scripts/tele/tmc"

- platform: command_line
  name: nt1
  command: "cat /home/homeassistant/.homeassistant/scripts/tele/nt1"

- platform: command_line
  name: nrj12
  command: "cat /home/homeassistant/.homeassistant/scripts/tele/nrj12"

- platform: command_line
  name: lcp
  command: "cat /home/homeassistant/.homeassistant/scripts/tele/lcp"

- platform: command_line
  name: fr4
  command: "cat /home/homeassistant/.homeassistant/scripts/tele/fr4"

- platform: speedtest
  hour:
    - 8
    - 12
    - 16
    - 20
    - 23
    - 4
  monitored_conditions:
    - ping
    - download
    - upload
