  default_view:
    view: yes
    icon: mdi:home
    entities:
      - group.ymeteotoday
      - group.automations
  ymeteotoday:
    name: Meteo
    entities:
      - sensor.sun_state
      - sensor.forecast
      - sensor.yweather_humidity
      - sensor.yweather_temperature
      - sensor.yweather_wind_speed
      - sensor.yweather_visibility
  automations:
    name: Automations
    entities:
      - input_boolean.bonjour
      - input_boolean.lumieresalon
      - input_boolean.volets
      - input_boolean.poubelles
      - script.demarre_robot_aspi
      - script.volet_chambre_parents
