- alias: "Chromecast paused"
  trigger:
    platform: state
    entity_id: media_player.chromecast_salon
    from: 'playing'
  condition:
    - condition: state
      entity_id: light.salon_tele
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: group.lumieressalon
      data:
        brightness: 255
- alias: "Chromecast playing"
  trigger:
    platform: state
    entity_id: media_player.chromecast_salon
    to: 'playing'
  condition:
    - condition: state
      entity_id: light.salon_tele
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: group.lumieressalon
      data:
        transition: 50
        brightness: 15

- alias: "Retour maison Seb"
  trigger:
   - platform: state
     entity_id: sensor.nutseb
     from: 'away'
     to: 'home'
  condition:
    - condition: time
      after: '16:00'
      before: '23:00'
  action:
    - delay:
        seconds: 20
    - service: tts.google_say
      entity_id: media_player.salon
      data_template: 
        message: "{{ ['Heureuse de vous voir monsieur','Bon retour à la maison, monsieur'] | random }}. J'espère que votre journée a été agréable."
        cache: false
