- alias: Poubelles a sortir
  trigger:
    platform: state
    entity_id: sensor.poubelles
    to: 'on'
    from: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.poubelles
      state: 'on'
    - condition: state
      entity_id: input_boolean.vacances
      state: 'off'
  action:
    - service: notify.notifier_seb
      data:
        message: 'Monsieur, il faudrait sortir les {{ states.calendar.ordures.attributes.message }}.'
    - service: notify.notifier_klem
      data:
        message: 'Mademoiselle, il faudrait sortir les {{ states.calendar.ordures.attributes.message }}.'

