- alias: Wake Me Up
  trigger:
    platform: time
    minutes: '/1'
    seconds: 0
  condition:
    - condition: state
      entity_id: input_boolean.alarmstatus
      state: 'on'
    - condition: template
      value_template: '{{ now().strftime("%H:%M") == states.sensor.alarm_time.state }}'
    - condition: state
      entity_id: calendar.jours_feries_en_france
      state: 'off'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: notify.notifier_seb
      data:
        message: "{{ ['Bonjour','Bonjour Monsieur','Salut Sébastien'] | random }}. Il faut se lever. Il est {{ states.sensor.alarm_time.state }}. La température exterieure est de {{ states.sensor.yweather_temperature.state }} degrés. La météo prévoit {{ states.sensor.forecast.state }}. Il vous faudra {{ states.sensor.maps_domicile_travail.state }} minutes pour aller au travail."
    - service: light.turn_on
      entity_id:
        - light.chambreseb
      data:
        brightness: 10 
    - delay:
        seconds: 30
    - service: light.turn_on
      entity_id:
        - light.chambreseb
      data:
        brightness: 15
    - delay:
        seconds: 30
    - service: light.turn_on
      entity_id:
        - light.chambreseb
      data:
        brightness: 20 

