- alias: Wake Me Up
  trigger:
    platform: time
    minutes: '/1'
    seconds: 0
  condition:
    - condition: state
      entity_id: input_boolean.alarmstatus
      state: 'on'
    - condition: template
      value_template: '{{ now().strftime("%H:%M") == states.sensor.alarm_time.state }}'
    - condition: state
      entity_id: calendar.jours_feries_en_france
      state: 'off'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: homeassistant.turn_on
      entity_id:
        - light.chambreseb
      data:
        brightness: 2
    - delay: 00:00:35
    - service: homeassistant.turn_on
      entity_id:
        - light.chambreseb
      data:
        brightness: 10
    - delay: 00:00:35
    - service: homeassistant.turn_on
      entity_id:
        - light.chambreseb
      data:
        brightness: 20 
    - service: notify.notifier_seb
      data:
        message: 'Bonjour. Il faut se lever, il est {{ states.sensor.alarm_time.state }}. La temperature exterieure est de {{ states.sensor.yweather_temperature.state }} degrés et la météo prévoit {{ states.sensor.forecast.state }}.'

