- alias: 'Demande des infos traffic'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/trafficseb'
  action:
    - service: notify.notifier_seb
      data:
        message: "Monsieur, Il vous faudra {{ states.sensor.maps_travail_domicile_seb.state }} minutes pour rentrer du travail."

- alias: 'Demande des infos traffic'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/trafficklem'
  action:
    - service: notify.notifier_klem
      data:
        message: "Mademoiselle, Il vous faudra {{ states.sensor.maps_travail_domicile_klem.state }} minutes pour rentrer du travail."

- alias: 'Aide'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/aide'
  action:
    - service: notify.notifier_seb
      data:
        message: "Voici la liste des commandes."
        data:
          keyboard:
            - '/volets'
            - '/vacances'
            - '/trafficseb'
            - '/trafficklem'
    - service: notify.notifier_klem
      data:
        message: "Voici la liste des commandes."
        data:
          keyboard:
            - '/volets'
            - '/vacances'
            - '/trafficseb'
            - '/trafficklem'
            
- alias: 'Depart de la maison seb'
  hide_entity: true
  trigger:
   - platform: state
     entity_id: sensor.nutseb
     from: 'home'
     to: 'away'
  condition:
    - condition: time
      after: '6:00'
      before: '9:00'
  action:
    - service: notify.notifier_seb
      data:
        message: "Bonne journée Monsieur. Il vous faudra {{ states.sensor.maps_domicile_travail_seb.state }} minutes pour aller au travail."
 
- alias: 'Depart de la maison klem'
  hide_entity: true
  trigger:
   - platform: state
     entity_id: sensor.beaconklem
     from: 'home'
     to: 'away'
  condition:
    - condition: time
      after: '7:00'
      before: '9:00'
  action:
    - service: notify.notifier_klem
      data:
        message: "Bonne journée klem. Il vous faudra {{ states.sensor.maps_domicile_travail_klem.state }} minutes pour aller au travail."
