- alias: 'Demande du mode vacances'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/vacances'
  action:
    - service: notify.notifier_seb
      data:
        message: 'Monsieur, Voulez vous changer le mode vacances ?'
        data:
          keyboard:
            - '/Activer'
            - '/Desactiver'

- alias: 'Passage en mode vacance'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/Activer'
  action:
    - service: notify.notifier_seb
      data:
        message: 'Activation du mode vacance.'
    - service: homeassistant.turn_on
      entity_id: input_boolean.vacances
    - service: switch.turn_off
      entity_id: switch.chaudiere
    - service: switch.turn_off
      entity_id: switch.television
    - service: switch.turn_off
      entity_id: switch.wii

- alias: 'Passage en mode vacance'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/Desactiver'
  action:
    - service: notify.notifier_seb
      data:
        message: 'Desactivation du mode vacance.'
    - service: homeassistant.turn_off
      entity_id: input_boolean.vacances
    - service: switch.turn_on
      entity_id: switch.chaudiere
    - service: switch.turn_on
      entity_id: switch.television

