- alias: fermer les volets du salon quand la nuit tombe
  trigger:
#    platform: sun
#    event: sunset
#    offset: "-00:10:00"
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 2.5
  condition:
    - condition: state
      entity_id: input_boolean.volets
      state: 'on'
#    - condition: state
#      entity_id: sensor.broadlinklight
#      state: 'sombre' 
  action:
    - service: light.turn_on
      entity_id: group.lumieressalon
      data:
        brightness: 254
    - service: switch.turn_off
      entity_id: switch.volet_salon
    - service: notify.notifier_seb
      data:
        message: Les volets du salon sont fermes !
- alias: ouvrir les volets du salon quand le jour se leve
  trigger:
    platform: sun
    event: sunrise
  condition:
    - condition: state
      entity_id: input_boolean.volets
      state: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.volet_salon
