- alias: fermer les volets du salon quand la nuit tombe
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 0.2
  condition:
    - condition: state
      entity_id: input_boolean.volets
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.volet_salon
    - service: switch.turn_off
      entity_id: switch.volet_chambre

- alias: ouvrir les volets du salon quand le jour se leve et qu'il n'y a pas d'invité
  trigger:
    platform: sun
    event: sunrise
  condition:
    - condition: state
      entity_id: input_boolean.volets
      state: 'on'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.volet_salon

    
- alias: 'Demande du mode volets'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/volets'
  action:
    - service: notify.notifier_seb
      data:
        message: "Monsieur, {%- if states.input_boolean.volets.status == 'on' -%} la gestion automatique des volets est activée. {%- else -%} la gestion automatique des volets est désactivée.{%- endif -%} Voulez vous changer la gestion automatique des volets ?"
        data:
          keyboard:
            - '/ActiverVolets'
            - '/DesactiverVolets'

- alias: 'Activation de la gestion automatique des volets'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/ActiverVolets'
  action:
    - service: notify.notifier_seb
      data:
        message: 'Activation de la gestion automatique des volets'
    - service: homeassistant.turn_on
      entity_id: input_boolean.volets

- alias: 'Desactivation de la gestion automatique des volets'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/DesactiverVolets'
  action:
    - service: notify.notifier_seb
      data:
        message: 'Desactivation de la gestion automatique des volets'
    - service: homeassistant.turn_off
      entity_id: input_boolean.volets

- alias: fermer en partie les volets si trop chaud
  trigger:
    platform: state
    entity_id: sensor.broadlinklight 
    to: 'lumineux'
  condition:
    - condition: state
      entity_id: input_boolean.volets
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.broadlink_sensor_temperature
      above: 27.0
  action:
    - service: switch.turn_off
      entity_id: switch.volet_salon
    - delay:
        seconds: 15
    - service: switch.turn_off
      entity_id: switch.volet_salon

